### ISSUE TITLE
ns-train tetra-nerf: error: argument, invalid choice from 

### ISSUE THREAD

**Issue by sandy-ssdut** [jkulhanek/tetra-nerf#2]
when i train custom data like this:

![image](https://user-images.githubusercontent.com/6028443/236371922-d702e39f-473b-4f1d-8f0a-d2b1d9cf3d78.png)

There is a error 

![image](https://user-images.githubusercontent.com/6028443/236371836-f4ce37a9-b5d3-4a44-af06-205ff93433ed.png)

How can i fix it ?

**Comment by jkulhanek** [comment]
Please post the command you used and describe how you installed tetra-nerf

**Comment by jkulhanek** [comment]
Sorry, the command should be:
```
ns-train tetra-nerf --pipeline.model.tetrahedra-path ... minimal-parser --data ...
```

I have updated the README. Where did you get this "old" command from?

**Comment by WHao-0923** [comment]
Sorry, but mine still does not work with this command. It prints the following error: 
ns-train tetra-nerf: error: argument [{pipeline.datamanager.camera-optimizer:camera-optimizer-config,pipeline.datamanager.camera-optimizer:None}]: invalid choice: './data/sparse.th' (choose from 'pipeline.datamanager.camera-optimizer:camera-optimizer-config', 'pipeline.datamanager.camera-optimizer:None')

**Comment by WHao-0923** [comment]
> Can you please post the output of `ns-train tetra-nerf —help`?

![image](https://github.com/jkulhanek/tetra-nerf/assets/78854240/001aa749-e3cf-49a3-886f-9e378bd7a792)
![image](https://github.com/jkulhanek/tetra-nerf/assets/78854240/5d7d72eb-e106-40c8-ad5f-5fe3655c8f4a)

**Comment by jkulhanek** [comment]
Can you also post the output of `ns-train —help`?

**Comment by WHao-0923** [comment]
> Can you also post the output of `ns-train —help`?
This is the output of ns-train --help
![image](https://github.com/jkulhanek/tetra-nerf/assets/78854240/0386d549-a332-417d-bb39-60237db9438b)
![image](https://github.com/jkulhanek/tetra-nerf/assets/78854240/6c49bbcf-4544-4240-9565-dd328241d47d)

**Comment by jkulhanek** [comment]
It seems like tetra-nerf is not installed. How did you install it?

**Comment by WHao-0923** [comment]
> It seems like tetra-nerf is not installed. How did you install it?

Sorry, seems like the tetra-nerf is not installed properly. However, after I pip install the tetra-nerf from the readme, the training command gives me the following error:
<img width="492" alt="Screenshot 2023-08-15 at 4 19 09 PM" src="https://github.com/jkulhanek/tetra-nerf/assets/78854240/69f76a04-ddee-42ca-94b9-7b0c3cc9e2b6">
I encountered this error before, and I reinstalled everything. Do you know if this has anything to do with the order of installation?

**Comment by jkulhanek** [comment]
Can you please git clone the repo and run `cmake . && make`?
